name: bijective-transformers
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  
  # Core ML Framework
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-lightning
  
  # HuggingFace ecosystem
  - transformers>=4.30.0
  - tokenizers
  - datasets
  - accelerate
  
  # Numerical/Scientific computing
  - numpy<2.0,>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  
  # Tensor manipulation and utilities
  - einops>=0.6.0
  - tensorboard
  - tqdm
  
  # Development tools
  - jupyter
  - jupyterlab
  - ipython
  - black
  - isort
  - flake8
  - pytest
  - pytest-cov
  
  # Version control and utilities
  - git
  - wget
  - unzip
  
  # Pip-only dependencies
  - pip:
    - wandb>=0.15.0
    - nflows>=0.14
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0
    - rich>=13.0.0
    - typer>=0.9.0
    - FrEIA>=0.2
    - torch-ema>=0.3.0
    - torchmetrics>=0.11.0
